apiVersion: v1
kind: ConfigMap
metadata:
  name: mcmf-config
  namespace: mcmf-system
data:
  config.yaml: |
    simulation:
      default_n_simulations: 10000
      default_n_steps: 252
      use_antithetic_variates: true
      random_seed: 42
    
    risk_analytics:
      confidence_levels: [0.95, 0.99, 0.999]
      lookback_window: 252
      decay_factor: 0.94
    
    optimization:
      use_gpu: false
      memory_optimization: true
      parallel_processing: true
    
    logging:
      level: INFO
      format: json
      
  nginx.conf: |
    upstream mcmf_backend {
        least_conn;
        server mcmf-app-0.mcmf-service:8501;
        server mcmf-app-1.mcmf-service:8501;
        server mcmf-app-2.mcmf-service:8501;
    }
    
    server {
        listen 80;
        server_name mcmf.example.com;
        
        location / {
            proxy_pass http://mcmf_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
