apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcmf-app
  namespace: mcmf-system
  labels:
    app: mcmf-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mcmf-app
  template:
    metadata:
      labels:
        app: mcmf-app
    spec:
      containers:
      - name: mcmf-app
        image: mcmf-system:latest
        ports:
        - containerPort: 8501
          name: streamlit
        - containerPort: 8050
          name: dash
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: mcmf-secrets
              key: postgres-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mcmf-secrets
              key: secret-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: mcmf-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: mcmf-data-pvc
